[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo='tpope/vim-fugitive'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']
hook_source = '''
let g:javascript_plugin_flow = 1
'''

# [[plugins]]
# repo = 'othree/yajs.vim'
# on_ft = [ 'javascript', 'javascript.jsx' ]
#
# [[plugins]]
# repo = 'othree/es.next.syntax.vim'
# on_ft = [ 'javascript', 'javascript.jsx' ]

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = [ 'javascript', 'javascript.jsx' ]
# hook_source = '''
# let g:vim_jsx_pretty_colorful_config = 1
# '''


# [[plugins]]
# repo = 'mxw/vim-jsx'
# on_ft = 'jsx'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo='scrooloose/nerdtree'

[[plugins]]
repo='flowtype/vim-flow'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo='w0rp/ale'

[[plugins]]
repo='Shougo/neosnippet'

[[plugins]]
repo='Shougo/neosnippet-snippets'

[[plugins]]
repo = 'wakatime/vim-wakatime'
